name: Github repos mirror periodic job
on:
  push:
    # Runs at every pull requests submitted in master branch 
    branches: master
  pull_request:
    branches: master
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the Github organization repos to Gitee.
      uses: Yikun/hub-mirror-action@master
      with:
        src: 'github/qiuming520'
        dst: 'gitee/qiuming520'
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        timeout: 600
        debug: true
        account_type: user
        force_update: true
        static_list: 'qingwave.github.io'
